GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWEiOiJOdWdyYWhhIEFkaGl0YW1hIiwiZW1haWwiOiJ0ZXNAZ21haWwuY29tIiwiaWF0IjoxNjg4NTQ5MjQ1LCJleHAiOjE2ODg1NDkyNzV9.f4DL49ttFGz5zWgt7TuqBtN_vzL9v70n3FzudAr3wmw

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "nama_lengkap": "Muhammad Rifqi",
    "email": "Muhammad@Rifqi.com",
    "password": "123456",
    "confirmPassowrd": "123456"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "tes@gmail.com",
    "password": "123456"
}

###
GET http://localhost:3000/users/token

###
DELETE http://localhost:3000/users/logout

###

GET http://localhost:3000/scholarships

###
GET http://localhost:3000/scholarships?urut_berdasarkan=jumlah_pencarian

###
GET http://localhost:3000/scholarships?tipe=full

###
GET http://localhost:3000/scholarships?negara_tujuan=In

###
GET http://localhost:3000/scholarships?degree=S1&negara_tujuan=Am

###
GET http://localhost:3000/scholarships?degree=S1&tipe=par

###
GET http://localhost:3000/scholarships?degree=S3&urut_berdasarkan=jumlah_pencarian

###
GET http://localhost:3000/scholarships?negara_tujuan=In&tipe=full

###
GET http://localhost:3000/scholarships?negara_tujuan=In&urut_berdasarkan=jumlah_pencarian

###
GET http://localhost:3000/scholarships?tipe=full&urut_berdasarkan=jumlah_pencarian

###
GET http://localhost:3000/scholarships?degree=s1&negara_tujuan=in&tipe=full&urut_berdasarkan=tanggal_akhir_daftar

###
GET http://localhost:3000/profil-jurusan

###
GET http://localhost:3000/profil-jurusan/621942f9-199a-11ee-8c62-107b44e05fcc

###
GET http://localhost:3000/profil-jurusan/621942f9-199a-11ee-8c62-107b44e05fcc/10ad72c2-53f7-4d50-a250-fc2beee1101b

###
GET http://localhost:3000/profil-jurusan/621942f9-199a-11ee-8c62-107b44e05fcc/10ad72c2-53f7-4d50-a250-fc2beee1101b/tempat-kuliah